name: Generate Car Contribution SVG

on:
  push:
    branches:
      - main

jobs:
  generate_svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Generate car animation SVG
        run: npm run generate-car-svg

      - name: Commit and push SVG
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add output/github-car-dark.svg
          git commit -m 'Update car contribution SVG'
          git push
