name: Generate Car Contribution SVG

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # daily at midnight UTC

jobs:
  generate_svg:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Generate Car Animation SVG
        run: npm run generate-car-svg

      - name: Commit and Push SVG to output branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add output/github-car-dark.svg
          git commit -m 'Update car contribution SVG' || echo "No changes to commit"
          git push origin HEAD:output
